version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"

  - package-ecosystem: "docker"
    directories:
      - "/docker/server"
      - "/docker/certs-init"
      - "/docker/fixtures"
      - "/docker/issuer"
    schedule:
      interval: "weekly"
